# Generated by Django 3.2.12 on 2022-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название песни')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/music', verbose_name='Загрузить песню')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
