# Generated by Django 4.0.4 on 2022-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название песни')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='Music', verbose_name='Загрузить песню')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='MusicPosters', verbose_name='Загрузить постер')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
