# Generated by Django 3.2.12 on 2022-04-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название плэй-листа')),
                ('eighth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eighth', to='music.music')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='music.music')),
                ('fiveth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiveth', to='music.music')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth', to='music.music')),
                ('ninth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninth', to='music.music')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='music.music')),
                ('seventh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seventh', to='music.music')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixth', to='music.music')),
                ('tenth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenth', to='music.music')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='music.music')),
            ],
        ),
    ]
