# Generated by Django 4.0.4 on 2022-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название альбома')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='MusicPosters', verbose_name='Загрузить постер')),
                ('pub_date', models.DateField()),
                ('songs', models.ManyToManyField(to='music.music')),
            ],
        ),
    ]
