# Generated by Django 4.0.4 on 2022-06-23 17:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текси')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст песни'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='PlaylistPosters', verbose_name='Загрузить постер'),
        ),
    ]
