# Generated by Django 4.0.4 on 2022-06-30 15:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_verse_alter_music_text_alter_playlist_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('desc', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='PlaylistPosters', verbose_name='Загрузить постер')),
                ('video', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео (YouTube)')),
                ('date_time', models.DateTimeField(verbose_name='Дата проведения')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('songs', models.ManyToManyField(to='music.music')),
            ],
        ),
    ]
