# Generated by Django 4.0.4 on 2022-07-05 16:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_pub_date_alter_playlist_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'Главная страница'), ('music', 'Песни'), ('verse', 'Стихи'), ('concerts', 'Концерты'), ('press', 'Пресс-релиз')], max_length=300, verbose_name='На какой странице находится текст?')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
    ]
