# Generated by Django 4.0.4 on 2022-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плэйлист', 'verbose_name_plural': 'Плэйлисты'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'verbose_name': 'Стих', 'verbose_name_plural': 'Стихи'},
        ),
        migrations.AddField(
            model_name='concert',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место проводения'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='music',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
